### ISSUE TITLE
Jak zarzadzic dostepem do commitow i ich weryfikacja?

### ISSUE THREAD

**Issue by bkt1916** [DevOps-Together/project-wojtas#4]
Pytanie - w jakim stopniu i gdzie możemy zarządzać dostępem i decydować czy ktoś może commitować i czy może potwierdzać zmiany?

**Comment by wojtas91** [comment]
@bkt1916 nie bardzo da sie to ustawic  - ogolnie ja i @bishtou mamy admina na tym repo i reszta ma write.
Jesli chcesz to moge wylaczyc commitowanie do main i wtedy flow bedzie mniej wiecej taki:
nowy brach od main -> zmiany -> pull request -> ktos musi dac approve -> merged do main

**Comment by bkt1916** [comment]
Spoko, mysle ze to wszystko jedno, po prostu chcialem sie dowiedziec jakie sa mozliwosci - z tego co czytalem gitlab w tym zakresie jest bardziej ciekawy.?
